#pragma once

#include <algorithm>
#include <iostream>
#include <vector>
#include <iterator>
#include <map>
#include <stack>
#include <typeinfo>
#include <utility>
#include <functional>
#include <cstring>
#include <climits>
#include <limits>
#include <stdexcept>
#include <sstream>
#include <memory>
#include <utility>
#include <string>
#include <deque>
#include <cstddef>
#include <type_traits>
#include <random>
#include <numeric>
#include <string_view>

#include "reverse_iterator.hpp"
#include "utils.hpp"
#include "vector_iterator.hpp"
#include "vector.hpp"

int my_vector_tests(void);
int my_vector_assign(void);
int my_vector_at(void);
int my_vector_at_const(void);
int my_vector_push_pop(void);
int my_vector_copy_construct(void);
int my_vector_erase(void);
int my_vector_insert(void);
