#pragma once

#include <algorithm>
#include <iostream>
#include <vector>
#include <iterator>
#include <map>
#include <stack>
#include <typeinfo>
#include <utility>
#include <functional>
#include <cstring>
#include <climits>
#include <limits>
#include <stdexcept>
#include <sstream>
#include <memory>
#include <utility>
#include <string>
#include <deque>
#include <cstddef>
#include <type_traits>
#include <random>
#include <numeric>
#include <string_view>